### ISSUE TITLE
New Zombie Types

### ISSUE THREAD

**Issue by Jiskster** [Jiskster/Zombie-Escape#14]
Zombie alpha code may need to be removed, and replaced with zombie type.
**- Ideas:**
- Fast zombie. (high acceleration but weak) (has 100 hp)
- Poison Zombie. ( 5 hp taken per second for 10 seconds ) (has 300 hp)
- Dark Zombie ; (Zombie that goes invisible like revenger, has 500 hp)
- Tank Zombie (huge, has 3000 health)
- Golden Zombie (glows gold obviously, drops food when killed, has 1200 hp,)

**Comment by NeoniusNext** [comment]
F Poison,dark,gold

**Comment by Jiskster** [comment]
this feature has been added for a while but poison dark and gold has been removed. even though poison was never playable
