### ISSUE TITLE
RailAI bots not turning into zombies

### ISSUE THREAD

**Issue by AngrySonics** [Jiskster/Zombie-Escape#36]
Let me get straight to the point:
When a RailAI bot is chosen to be a zombie, they will die as normal, but they won't be assigned to the "Red Team" upon respawning. They will also keep their previous skin. See attached pictures.

This might also happen with normal bots, but I have no clue if it actually does.

TLDR:
Expected behavior: RailAI bot becomes zombie
Actual behavior: RailAI bot stays as survivor

![Player list after respawning. The Tails bot is not a zombie.](https://github.com/Jiskster/Zombie-Escape/assets/112799592/1022f28a-8278-43d1-8515-ae4b1f6d646d)
![In the HUD, you can see that there are 0 zombies and 2 survivors, despite the game already starting.](https://github.com/Jiskster/Zombie-Escape/assets/112799592/417da174-f7fb-4b7c-bd89-b5ef87e7f66a)

**Comment by Jiskster** [comment]
I discontinued railai not so long ago, but I can add general bot support in a future verison.

**Comment by Jiskster** [comment]
no bot support
